In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype=np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=np.float64)

In [3]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [4]:
X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])

In [32]:
def calc_logloss(y, y_pred):
    #добавил обработку с np.clip
    np.clip(y,1e-10,1-1e-10,out=y)
    np.clip(y_pred,1e-10,1-1e-10,out=y_pred)
    print(y,y_pred)
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [33]:
y1 = np.array([1, 0])
y_pred1 = np.array([1, 0.2])
calc_logloss(y1, y_pred1)

[0 0] [1.  0.2]


11.62449719925715

In [7]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [8]:
z = np.linspace(-10, 10, 101)

In [9]:
probabilities = sigmoid(z)

In [40]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [67]:
W = eval_model(X_st, y, iterations=475, eta=1e-2)
#iterations=475, eta=1e-2
W

[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.77678197 0.81967624 0.95100063 0.69583154 0.97730047 0.85643521
 0.9937923  0.99364588 0.76498816 0.9644164 ]
0 [ 0.49292028 -0.15277306  0.64741473  1.51736839] 1.1785958344941945
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.77264637 0.81613031 0.94890878 0.67824944 0.97595616 0.85528095
 0.99318722 0.99250379 0.76070651 0.96286989]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.76849787 0.81256426 0.94675231 0.66031069 0.97454635 0.85413033
 0.9925294  0.99117039 0.75641443 0.96127298]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.76433932 0.80898041 0.94453126 0.64207273 0.97306933 0.85298382
 0.99181514 0.98961706 0.75211492 0.95962547]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.76017366 0.80538118 0.94224583 0.6235963  0.9715235  0.85184191
 0.99104064 0.98781175 0.74781102 0.95792726]
[1.e

[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.4979849  0.57630702 0.72239802 0.06208729 0.7933248  0.76525381
 0.78204359 0.18030518 0.47826784 0.79429352]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.49772703 0.57610681 0.72226894 0.06203582 0.79334242 0.76512365
 0.78209373 0.18043456 0.47799727 0.79423158]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.4974698  0.57590709 0.72214032 0.06198447 0.79336014 0.7649938
 0.78214398 0.18056376 0.47772736 0.79416993]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.4972132  0.57570783 0.72201213 0.06193324 0.79337793 0.76486428
 0.78219433 0.18069278 0.47745813 0.79410856]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.49695722 0.57550905 0.72188439 0.06188213 0.7933958  0.76473506
 0.78224477 0.18082162 0.47718955 0.79404747]
[1.e-10 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e-10 1.e+00 1.e+00] [0.4

array([ 0.05290274, -0.71956471,  0.85041124,  1.32143581])

In [68]:
def calc_pred_proba(W, X):
    z = np.dot(W,X)
    return 1/(1 + np.exp(-z))

#Возвращает предсказанную вероятность

In [ ]:
def calc_pred(W, X):
    y_pred = calc_pred_proba(W,X)
    y_pred = np.where(y_pred>0.5,1,0)
    return y_pred

#Возвращает классы