# 2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15


In [2]:
import numpy as np
A = np.array([[1,2,-1],[3,-4,0],[8,-5,2],[2,0,-5],[11,4,-7]])
B = np.array([1,7,12,7,15])
np.linalg.lstsq(A,B)

C:\Users\HOME\AppData\Local\Temp\ipykernel_8324\2360001819.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A,B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

# 3. Сколько решений имеет линейная система:


Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 


In [11]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
C

array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  2],
       [ 7,  8,  9,  1]])

In [12]:
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 3)

Система не имеет решений, поскольку ранг основной матрицы меньше ранга расширенной матрицы.

In [13]:
# Изьеним В, чтобы были решения
B = np.array([12, 2, 3])
np.linalg.solve(A, B)

array([-4.95395959e+16,  9.90791918e+16, -4.95395959e+16])

# 4. Вычислите LU-разложение матрицы:

In [8]:
import scipy
import scipy.linalg
A = np.array([[1,2,3],[2,16,21],[4,28,73]])
P,L,U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P,A) - np.dot(L,U))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ 2. 16. 21.]
 [ 4. 28. 73.]
 [ 1.  2.  3.]]


# 5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1  
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 


In [10]:
import matplotlib as plt

def Q(x,y,z):
    return (x**2+y**2+z**2)

A = np.array([[1,2,-1],[8,-5,2]])
B = np.array([1,12])
np.linalg.lstsq(A,B)

C:\Users\HOME\AppData\Local\Temp\ipykernel_8324\46044015.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A,B)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

# 6. Найдите одно из псевдорешений вырожденной системы:


In [14]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])
B = np.array([2, 5, 11])
np.linalg.lstsq(A, B)

C:\Users\HOME\AppData\Local\Temp\ipykernel_8324\995244347.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.25,  0.5 , -0.25]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))